### ISSUE TITLE
Command line arguments search is not implemented

### ISSUE THREAD

**Issue by JarLob** [doyensec/electronegativity#22]
Checks like 'Additionally, search for the runtime flag —disable-web-security in
package.json, and within the application codebase.' are not implemented yet.

There is already package.json check for electron version. But it is not clear what to use for the search within codebase: full text grep or just string literals.

**Comment by phosphore** [comment]
Are there other ways to set these in the codebase besides `app.commandLine.appendArgument()` or `app.commandLine.appendSwitch`?

Just to wrap up, Electronegativity should be looking for the following additional insecure flags (reporting them with `manualReview: false`):
* `--disable-web-security`
* `--ignore-certificate-errors`

How about if we also report the presence of these flags (`manualReview: true`):
* `--js-flags`
* `--auth-server-whitelist`
* `--inspect`
* `--inspect-brk`
* `--remote-debugging-port`

[(Full list here)](https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md)

**Comment by ikkisoft** [comment]
> Are there other ways to set these in the codebase besides `app.commandLine.appendArgument()` or `app.commandLine.appendSwitch()`?

Not that I am aware of.

> instead of just reporting everything?
> [(Full list here)](https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md)

There're definitely more dangerous args, like for example ```host-rules``` since it allows host remapping for MiTM. 

Blacklist will probably reduce the number of false positives triggered by the tool, but it's going to be difficult to keep the list in sync with the framework AND we need to manually review each flag and think about possible abuses. The complete list is pretty big: https://github.com/electron/electron/blob/fe7947da90a6e161e731a10e4246a07b7d71dea3/atom/app/command_line_args.cc#L55
